### PR TITLE
Improve Notification Filters

### PR DESCRIPTION
**Pull request by dshanske**
The attached changes not only improve usability, but readability. I found I could not effectively hook on to the filters as previously designed.

### CODE REVIEW

**Comment by cklosowski** [comment]
Looks good. Thanks.

**Comment by cklosowski** [comment]
@dshanske Just as an FYI, you had removed some key parameters for the `sprintf` function to work. I've fixed them in the commit listed above.

**Comment by dshanske** [comment]
I keep telling myself, don't commit at 3am.

**Comment by dshanske** [comment]
How often do you push to the WordPress.org repository?

**Comment by cklosowski** [comment]
@dshanske when neeed, i'll probably push these up in the next few days. Need to look through some other local changes I have, for some minor improvements

**Comment by dshanske** [comment]
I have a custom comment type I want to support, if you are wondering what the goal is.

**Comment by cklosowski** [comment]
Makes sense. I've merged everything into the master branch if you want to pull that down with my changes and make sure it all still work?

**Pull request merged**
